import math

SPEED_MAX_W:float = 19.44
SPD_MAX_STD = 10.0

# Tank Challenge의 맵 크기
MAP_W = 300
MAP_H = 300

# [설계 파라미터]
LOOKAHEAD_POINTS = 4  # 경로 추종을 위한 앞의 N개 점
LIDAR_NUM   = 65
LIDAR_RANGE = 30
LIDAR_START = -math.pi
LIDAR_END   =  math.pi

# 상태: 플레이어 속도(방향빼고) + 경로 점들, 라이다 거리점수, 라이다 최근접 거리점수, 라이다 최근접 각도
OBSERVATION_IND_SPD        = 0
OBSERVATION_IND_GOAL_0     = 0 + 1
OBSERVATION_IND_GOAL_1     = 0 + 1 + (1 * LOOKAHEAD_POINTS)
OBSERVATION_IND_GOAL_2     = 0 + 1 + (2 * LOOKAHEAD_POINTS)
OBSERVATION_IND_SCALAR_S   = 0
OBSERVATION_IND_SCALAR_E   = 0 + 1 + (5 * LOOKAHEAD_POINTS)
OBSERVATION_DIM_SCALAR     = OBSERVATION_IND_SCALAR_E - OBSERVATION_IND_SCALAR_S

OBSERVATION_IND_LIDAR_DIS_S    = 0 + 1 + (5 * LOOKAHEAD_POINTS)
OBSERVATION_IND_LIDAR_DIS_E    = 0 + 1 + (5 * LOOKAHEAD_POINTS) + LIDAR_NUM
OBSERVATION_DIM_LIDAR          = LIDAR_NUM

OBSERVATION_DIM            = 0 + 1 + (5 * LOOKAHEAD_POINTS) + LIDAR_NUM
